### GET todos os fornecedores
GET http://localhost:5066/api/fornecedor
Accept: application/json

### GET fornecedor por id
GET http://localhost:5066/api/fornecedor/1
Accept: application/json

### POST cadastrar fornecedor (usando DTO)
POST http://localhost:5066/api/fornecedor/cadastro
Content-Type: application/json

{
  "nomeEmpresa": "Fornecedora Bebidas",
  "cnpj": "12345678000199",
  "emailCorporativo": "contato@Fornecedora.com",
  "senha": "senha123",
  "PorodutosFornecedor": [
    {
      "nome": "Água Mineral",
      "tipo": "Bebida",
      "preco": 2.50,
      "quantidadeEstoque": 100,
      "dataValidade": "2026-01-01T00:00:00"
    }
  ]
}

### POST produto para o fornecedor
POST http://localhost:5066/api/fornecedor/1/Produtos
Content-Type: application/json

{
  "nome": "Cerveja IPA",
  "tipo": "Bebida",
  "preco": 8.50,
  "quantidadeEstoque": 50,
  "dataValidade": "2025-12-31T00:00:00"
}

### PUT atualizar fornecedor (id 1)
PUT http://localhost:5066/api/fornecedor/3
Content-Type: application/json

{
  "nomeEmpresa": "fornecedor concorrente",
  "cnpj": "12345678000199",
  "emailCorporativo": "contato@fornecedor.com",
  "senhaHash": "$2a$11$ElCQKgH0I7bn23TmFeauNekK5yb6AIT0vb61IPQm/57J3lbi5AI0S"
}

### DELETE fornecedor (id 1)
DELETE http://localhost:5066/api/fornecedor/1


### GET busca de produto de fornecedor por id
GET http://localhost:5066/api/fornecedor/1/protutos
Accept: application/json
