### GET todos os fornecedores ou para pegar algum em especifico coloque "/{id}
GET http://localhost:5066/api/fornecedor
Accept: application/json

### POST cadastrar fornecedor (usando DTO)
POST http://localhost:5066/api/fornecedor/cadastro
Content-Type: application/json

{
  "nomeEmpresa": "Fornecedora Bebidas",
  "cnpj": "12345678000199",
  "emailCorporativo": "contato@fornecedora.com",
  "senha": "senha123",
  "ProdutosFornecedor": [
    {
      "nome": "Água Mineral",
      "tipo": "Bebida",
      "preco": 2.50,
      "quantidadeEstoque": 100,
      "dataValidade": "2026-01-01T00:00:00"
    },
    {
      "nome": "Cerveja IPA",
      "tipo": "Bebida",
      "preco": 7.90,
      "quantidadeEstoque": 80,
      "dataValidade": "2025-12-31T00:00:00"
    },
    {
      "nome": "Refrigerante Cola",
      "tipo": "Bebida",
      "preco": 4.50,
      "quantidadeEstoque": 120,
      "dataValidade": "2026-06-15T00:00:00"
    },
    {
      "nome": "Suco de Laranja",
      "tipo": "Bebida",
      "preco": 5.00,
      "quantidadeEstoque": 90,
      "dataValidade": "2026-02-20T00:00:00"
    },
    {
      "nome": "Energético PowerUp",
      "tipo": "Bebida",
      "preco": 8.00,
      "quantidadeEstoque": 70,
      "dataValidade": "2026-09-01T00:00:00"
    },
    {
      "nome": "Vinho Tinto",
      "tipo": "Bebida",
      "preco": 25.00,
      "quantidadeEstoque": 50,
      "dataValidade": "2027-01-01T00:00:00"
    },
    {
      "nome": "Vodka",
      "tipo": "Bebida",
      "preco": 30.00,
      "quantidadeEstoque": 60,
      "dataValidade": "2028-01-01T00:00:00"
    },
    {
      "nome": "Whisky",
      "tipo": "Bebida",
      "preco": 45.00,
      "quantidadeEstoque": 40,
      "dataValidade": "2028-05-10T00:00:00"
    },
    {
      "nome": "Cachaça Premium",
      "tipo": "Bebida",
      "preco": 18.00,
      "quantidadeEstoque": 75,
      "dataValidade": "2027-08-30T00:00:00"
    },
    {
      "nome": "Cerveja Lager",
      "tipo": "Bebida",
      "preco": 5.50,
      "quantidadeEstoque": 100,
      "dataValidade": "2025-11-20T00:00:00"
    }
  ]
}

### GET produto para o fornecedor
GET http://localhost:5066/api/fornecedor/1/produtos
Accept: application/json

### PUT atualizar fornecedor (id 1) caso o cadastro esteja errado
PUT http://localhost:5066/api/fornecedor/3
Content-Type: application/json

{
  "nomeEmpresa": "fornecedor concorrente",
  "cnpj": "12345678000199",
  "emailCorporativo": "contato@fornecedor.com",
  "senhaHash": "$2a$11$ElCQKgH0I7bn23TmFeauNekK5yb6AIT0vb61IPQm/57J3lbi5AI0S"
}

### DELETE fornecedor por (id 1) 
DELETE http://localhost:5066/api/fornecedor/1

### GET busca de produto de fornecedor por id
GET http://localhost:5066/api/fornecedor/1/protutos
Accept: application/json
